" ---------------------------------------------------------
" What I see on the screen:
" ---------------------------------------------------------

colorscheme slate
syntax on
set number
" set cursorline " Highlights the line the curser is at.
set ruler 
set showmatch
set incsearch
set nowrap
set visualbell
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
set wrap linebreak

" ---------------------------------------------------------
" search behavior
" ---------------------------------------------------------
set hlsearch
set ignorecase
set smartcase

" ---------------------------------------------------------
" Text formatting
" ---------------------------------------------------------

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smarttab
filetype indent on

" ---------------------------------------------------------
" editing behavior
" ---------------------------------------------------------

set nocompatible

" ---------------------------------------------------------
" file management etc. 
" ---------------------------------------------------------

set noswapfile
set wildignore=*.swp,*.bak,*.class

" ---------------------------------------------------------
" Run all pathogen plugins.
" ---------------------------------------------------------

execute pathogen#infect()

" ---------------------------------------------------------
" Configure Syntastic.
" ---------------------------------------------------------

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']

" ---------------------------------------------------------
" Configure NERDTree.
" ---------------------------------------------------------

map <C-n> :NERDTreeToggle<CR>

" ---------------------------------------------------------
" Airline config.
" ---------------------------------------------------------

set laststatus=2


